server:
  port: 8081
spring:
  application:
    name: schedule-notification
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
notification:
  days-before: 2
  scheduler:
    job-interval-ms: 60000
broker:
  exchange:
    name: schedule.direct.exchange
  create-queue:
    name: schedule.create
  update-queue:
    name: schedule.update
  cancel-queue:
    name: schedule.cancel